/** @format */
import { gql } from '@apollo/client';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import client from '../../apollo-client';

export async function getServerSideProps(context) {
  const id = parseInt(context.query.id);
  try {
    const { data, error } = await client.query({
      query: gql`
          query GetArticle{
            article(id: ${id}) {
                articleId
                title
                content
                author {
                  username
                }
            }
          }
        `,
    });

    if (error) console.log('[getServerSideProps][error] =>', error);
    return {
      props: {
        article: data.article,
      },
    };
  } catch (error) {
    return {
      props: {
        error: {
          message: "Attempting to retrieve an article that doesn't exist",
          articleId: id,
        },
      },
    };
  }
}

export default function ArticlePage({ article, error }) {
  if (error)
    return (
      <h1>
        Article id: {error.articleId} Error Message: {error.message}
      </h1>
    );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Kawthoolei.Dev!</a>
        </h1>
        <div key={article.articleId}>
          <h3>{article.title}</h3>
          <p>{article.content}</p>
          <span>Written by {article.author.username}</span>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
